apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-controller
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applicationsets/rollingsync/default
    repoURL: 'https://github.com/mervani/gitops-examples.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
