apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pricelistv2

patches:
  - patch: |
      - op: replace
        path: /subjects/0/namespace
        value: pricelistv2
    target:
      kind: RoleBinding 

resources:
- pricelist-config-ns.yaml
- pricelist-config-rb.yaml
- pricelist-config-job.yaml
